// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYHJGM9JdRYf3DoNVox5Yrcx_BS-GQBt0',
    appId: '1:149796411344:web:da4f650c825d8dd5d7cbd5',
    messagingSenderId: '149796411344',
    projectId: 'vikingfit-5ccb3',
    authDomain: 'vikingfit-5ccb3.firebaseapp.com',
    storageBucket: 'vikingfit-5ccb3.firebasestorage.app',
    measurementId: 'G-D45D6NP2M6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBxUQqyw_eToeCL9rMa7qCllY6vLySfiE',
    appId: '1:149796411344:android:6f74f4aaa11eac99d7cbd5',
    messagingSenderId: '149796411344',
    projectId: 'vikingfit-5ccb3',
    storageBucket: 'vikingfit-5ccb3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcRTwtEa3b_bIoFwe-ZBlxAhuMj4uJw-Y',
    appId: '1:149796411344:ios:d4cfd9c7858d2e91d7cbd5',
    messagingSenderId: '149796411344',
    projectId: 'vikingfit-5ccb3',
    storageBucket: 'vikingfit-5ccb3.firebasestorage.app',
    iosBundleId: 'com.example.nutriVikingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcRTwtEa3b_bIoFwe-ZBlxAhuMj4uJw-Y',
    appId: '1:149796411344:ios:d4cfd9c7858d2e91d7cbd5',
    messagingSenderId: '149796411344',
    projectId: 'vikingfit-5ccb3',
    storageBucket: 'vikingfit-5ccb3.firebasestorage.app',
    iosBundleId: 'com.example.nutriVikingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYHJGM9JdRYf3DoNVox5Yrcx_BS-GQBt0',
    appId: '1:149796411344:web:0a18930d5e4475bed7cbd5',
    messagingSenderId: '149796411344',
    projectId: 'vikingfit-5ccb3',
    authDomain: 'vikingfit-5ccb3.firebaseapp.com',
    storageBucket: 'vikingfit-5ccb3.firebasestorage.app',
    measurementId: 'G-29JHR75TRP',
  );

}